USE [master]
GO

/****** Object:  Database [Atm]    Script Date: 16/09/2023 18:09:39 ******/
CREATE DATABASE [Atm]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Atm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Atm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Atm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Atm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Atm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Atm] SET ARITHABORT OFF 
GO

ALTER DATABASE [Atm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Atm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Atm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Atm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Atm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Atm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Atm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Atm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Atm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Atm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Atm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Atm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Atm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Atm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Atm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Atm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Atm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Atm] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Atm] SET  MULTI_USER 
GO

ALTER DATABASE [Atm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Atm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Atm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Atm] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Atm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Atm] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Atm] SET  READ_WRITE 
GO

